### ISSUE TITLE
sort nodes oldest first in each

### ISSUE THREAD

**Issue by matti** [kontena/k8s-node-descale#15]
currently when MAX_NODES_COUNT=1 the descaler might not delete the oldest node.

somehow use this as sort key: https://github.com/kontena/k8s-node-descale/blob/master/lib/k8s_node_descale/command.rb#L67

**Comment by kke** [comment]
I suppose, replace the `nodes.each` above with something like:

```ruby
nodes.sort_by { |node| Time.xmlschema(node.metadata.creationTimestamp) }.each do |node|
```
